### PR TITLE
Feature: residual depth

### PR DESCRIPTION
**Pull request by DrumsnChocolate**

### CODE REVIEW

**Comment by DrumsnChocolate** [comment]
whoops, meant to open this on my own fork :wink:

**Comment by DrumsnChocolate** [comment]
@philipperemy I've forked your project and moved to python 3.12 because I want to explore the performance of the TCN in one of my own projects where I'm already using 3.12. I chose simply dropping the dependency on `tensorflow-addons`, which involved removing the option for `WeightNormalization` (I think for my project the other two normalization options are definitely sufficient). 

If you want to support python 3.12 (either without weightnormalization or by annexing it from tensorflow-addons in some way) or if you want to stay at 3.10 for now but still introduce a parameter for residual depth (like I'm doing here), I'm happy to contribute.

**Comment by philipperemy** [comment]
Hey, I guess we can drop the dependency on `tensorflow-addons`. That's a good idea. We don't need to support `weightnormalization` anymore. Or if there's any other easy way.. Can you make a PR? It'd be appreciated!

**Comment by DrumsnChocolate** [comment]
I opened a PR: #266 if you have any remarks, let me know!

**Pull request closed without merging**
