### PR TITLE
Support tf.keras

### PR DESCRIPTION
**Pull request by yu-iskw**
## Issue
https://github.com/philipperemy/keras-tcn/issues/73

## Overview
If an environment has tf.keras, tf.keras is preferentially used to pure keras.

## Possible issue
If an user wan to use pure keras but the environment is not a tensorflow backend, an error might occur.

### CODE REVIEW

**Comment by yu-iskw** [comment]
The namespace was wrong. I modified it. Can you take a look at it?

**Comment by mimxrt** [comment]
> ImportError: cannot import name 'Input' from 'tensorflow.keras.models' (unknown location)

change:
```
from tensorflow.keras.models import Input, Model
```
to
```
from tensorflow.keras import Input, Model
```

**Comment by mimxrt** [comment]
Another error:

```
/ws/miniconda3/lib/python3.7/site-packages/tcn/tcn.py in __call__(self, inputs, training)
    148                                              dropout_rate=self.dropout_rate,
    149                                              kernel_initializer=self.kernel_initializer,
--> 150                                              use_batch_norm=self.use_batch_norm)
    151                 skip_connections.append(skip_out)
    152         if self.use_skip_connections:

/ws/miniconda3/lib/python3.7/site-packages/tcn/tcn.py in residual_block(x, training, dilation_rate, nb_filters, kernel_size, padding, activation, dropout_rate, kernel_initializer, use_batch_norm)
     55     # 1x1 conv to match the shapes (channel dimension).
     56     prev_x = Conv1D(nb_filters, 1, padding='same')(prev_x)
---> 57     res_x = keras.layers.add([prev_x, x])
     58     res_x = Activation(activation)(res_x)
     59     return res_x, x

NameError: name 'keras' is not defined
```
I fixed it by removing the `keras.` prefix in two occasions and changing
```
import tensorflow.keras.layers
```
to
```
import tensorflow.keras.layers as layers
```

**Comment by yu-iskw** [comment]
@mimxrt Thank you for making sure of it. I have modified some including the tasks.

**Comment by philipperemy** [comment]
See https://github.com/philipperemy/keras-tcn/pull/94

**Pull request closed without merging**
