### PR TITLE
Tensorflow 2.0

### PR DESCRIPTION
**Pull request by philipperemy**

### CODE REVIEW

**Comment by Luux** [comment]
Doesn't that break compatibility with the "normal" keras without tf.keras and therefore other backends?
Idk if for example the MXNet backend works properly at the moment for keras-tcn, but using tensorflow.keras should make that impossible.

**Comment by philipperemy** [comment]
@Luux yeah that's why this branch is not going to be merged! Was just a request from someone who wanted to have a TF 2.0 support.

**Comment by beasteers** [comment]
According to F. Chollet, they're recommending that people migrate code from `keras` to `tf.keras` so I think it would be beneficial to do it if we're going to have to do it eventually.

Source: https://twitter.com/fchollet/status/1174019423541157888 

I guess the question is, how important are other backends for users?

**Comment by philipperemy** [comment]
Deprecated now.

**Pull request closed without merging**
